/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prueba;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int sumar (int n1,int n2){
        return n1+n2;
    }

    public int restar (int n1,int n2){
        return n1-n2;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
